import { Router } from 'express';
import { requireLogin, requireAdmin } from '../middleware/auth';
import statsRouter from './admin-stats';
import logsRouter from './admin-logs';
import pharmaciesRouter from './admin-pharmacies';
import riskRouter from './admin-risk';
import reportsRouter from './admin-reports';
import trustRouter from './admin-trust';
import uploadJobsRouter from './admin-upload-jobs';
import matchingRulesRouter from './admin-matching-rules';
import drugEquivalencesRouter from './admin-drug-equivalences';
import csvExportRouter from './admin-csv-export';
import userRequestsRouter from './admin-user-requests';
import groupsRouter from './admin-groups';
import alertsRouter from './admin-alerts';
import directMessagesRouter from './admin-direct-messages';
import bulkActionsRouter from './admin-bulk-actions';
import relationshipsRouter from './admin-relationships';
import notificationsRouter from './admin-notifications';
import openclawCommandsRouter from './admin-openclaw-commands';
import openclawConnectAdminRouter from './admin-openclaw-connect';
import pharmacyHealthRouter from './admin-pharmacy-health';
import matchingPerformanceRouter from './admin-matching-performance';
import uploadQualityRouter from './admin-upload-quality';
import auditRouter from './admin-audit';
import businessHoursRouter from './admin-business-hours';
import sloRouter from './admin-slo';
import cronStatusRouter from './admin-cron-status';

const router = Router();

router.use(requireLogin);
router.use(requireAdmin);

router.use(statsRouter);
router.use(logsRouter);
router.use(trustRouter);
router.use(matchingRulesRouter);
router.use(riskRouter);
router.use(reportsRouter);
router.use(pharmaciesRouter);
router.use(uploadJobsRouter);
router.use(drugEquivalencesRouter);
router.use(csvExportRouter);
router.use(userRequestsRouter);
router.use(groupsRouter);
router.use(alertsRouter);
router.use(directMessagesRouter);
router.use(bulkActionsRouter);
router.use(relationshipsRouter);
router.use(notificationsRouter);
router.use(openclawCommandsRouter);
router.use(openclawConnectAdminRouter);
router.use(pharmacyHealthRouter);
router.use(matchingPerformanceRouter);
router.use(uploadQualityRouter);
router.use(auditRouter);
router.use(businessHoursRouter);
router.use(sloRouter);

router.use(cronStatusRouter);

export default router;
